# Generated by Django 4.0.4 on 2023-09-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tcap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_stuff', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HierarchicalTerroristGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('tcap_terrorist_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcap.terroristgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_stuff', models.CharField(default='some other taxonomy stuff', max_length=30)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.content')),
                ('terrorist_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.hierarchicalterroristgroup')),
            ],
        ),
    ]
