# Generated by Django 4.0.4 on 2023-09-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcap', '0001_initial'),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HierarchicalTerroristGroup',
            new_name='TaxonomyTerroristGroup',
        ),
    ]
